### ISSUE TITLE
...borschik...

### ISSUE THREAD

**Issue by 3ABAPKA** [tadatuta-studio/magic-desktop-kiosk#1]
Здравствуйте!
Увидел в этом проекте `.borschik` и конструкцию для заморозки путей в нём.
Пересмотрел все файлы репозитария, но не увидел какие пути он должен замораживать. Точнее я искал конструкции как из примеров на [bem.info](https://ru.bem.info/articles/borschik/):

что-нить похожее на:

```
var prj = {};
/* borschik:include:components/cookie.js */
```

или на:  `new Image().src = borschik.link('i/bg/main.png')`
И т.д.
**Не могли б Вы показать как в этом проекте «работает» (не знаю как назвать, может используется) borschik?**

[В проекте, которым я пытался изучить BEM (может помните Вы мне помогали)](https://github.com/3ABAPKA/The-first-project-on-validation/commit/8273a94671821393170ba75cae1139983b1e3cdf), у меня не вышло использовать borschik. [Чего-то я делаю не верно](https://github.com/bem/bem-method/issues/365). Хотел этот код использовать в качестве подсказки, но опять неудача = ничего найти не смог.

**Comment by tadatuta** [comment]
В CSS `borschik` без дополнительных подсказок умеет «замораживать» все внешние файлы: `background: url()` и шрифты. Это возможно, т.к. в CSS заранее известно, как внешние файлы находить. В JS такая схема не сработает, т.к. невозможно определить, где путь к файлу, а где — просто строка и там приходится использовать `borschik.link()`.
